### ISSUE TITLE
Use new admin notice functions (WordPress 6.4)

### ISSUE THREAD

**Issue by rvdsteege** [pronamic/wp-pay-core#161]
New admin notice functions are introduced in WordPress 6.4:
- https://make.wordpress.org/core/2023/10/16/introducing-admin-notice-functions-in-wordpress-6-4/

> **New functions**
> `wp_get_admin_notice()`
> Returns the markup for an admin notice.
>
> `wp_admin_notice()`
> Outputs the markup for an admin notice.

We might want to update our code at some point, as I can imagine WordPress core also going to use these functions for updated admin notices UI in the future.

**Comment by remcotolsma** [comment]
👍 We try to provide support for the last 3 major releases of PHP and WordPress in our projects:
https://github.com/pronamic/wp-coding-standards

We are currently on WordPress 6.5, we could start using this from WordPress 6.6.

1. `6.4`  
2. `6.5`
3. `6.6`

We don't necessarily need to rewrite current code immediately:

> Code refactoring should not be done just because we can.

https://make.wordpress.org/core/handbook/contribute/code-refactoring/
