### ISSUE TITLE
Always show "Disable Recurring Payments", not just in "Debug Mode"

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pay-core#165]
Today I had to alert a customer to this setting, and I noticed that we only show this setting in debug mode.

_Internal HelpScout ticket: https://secure.helpscout.net/conversation/2454026625/26654?viewId=1425710_

https://github.com/pronamic/wp-pay-core/blob/c743a1506d01274286f51d23debf765004b17d6f/src/Admin/AdminSettings.php#L111-L125

The customer gave feedback that this is 'strange':

> had de optie Disable starting recurring payments at gateway ook niet gezien want eerst moet je de debug mode inschakelen om dit te kunnen zien, dat vind ik vreemd.

I agree with that, should we always show this option? How do you see this @rvdsteege?

**Comment by rvdsteege** [comment]
I agree that the option is not very visible (has bothered me too). To always show the 'Disable recurring payments' option could be an improvement, especially if the site has been cloned by the same person who has initially activated Pronamic Pay and therefore might have been on the plugin settings page before. For other cases, I think it will still be too late at the time the setting is discovered in the plugin settings. A better solution would be to make users aware of the setting on URL changes, as suggested in https://github.com/pronamic/wp-pay-core/issues/102.

Part of the underlying issue could also be that users do not always know/realise that recurring payments are started from within the site itself and not by the gateway. But it shouldn't make a difference _where_ payments are started, so we don't have to make that more clear as far as I'm concerned.
