### ISSUE TITLE
Regarding Cancel Subscription Function

### ISSUE THREAD

**Issue by knit-pay** [pronamic/wp-pay-core#41]
I think in the `handle_subscription_cancel` function, we should call the `cancel_subscription` function of Gateway also. In some payment gateway, we need to make an API call to inform the gateway that the subscription is canceled. Apart from this, is there any other way to make an API call while executing the `handle_subscription_cancel` function? Or is there an action similar to `pronamic_payment_status_update_` which we can use to execute a function when a subscription gets canceled? Please refer to the code mentioned below.

https://github.com/wp-pay/core/blob/88ac1e26ae754cb2366697023f38f6004dbd15bb/src/Subscriptions/SubscriptionsModule.php#L152

https://github.com/wp-pay/core/blob/88ac1e26ae754cb2366697023f38f6004dbd15bb/src/Core/Gateway.php#L431

**Comment by knit-pay** [comment]
Hello Team

Is there an update on this?

**Comment by rvdsteege** [comment]
Seems we don't use (and never have) the `Gateway::update_subscription()` and `Gateway::cancel_subscription()` methods ourselves. We might remove these, @remcotolsma?

https://github.com/pronamic/wp-pay-core/blob/f220aa2ee979389cfcae782ff643b681ff85013b/src/Core/Gateway.php#L244-L262

@knit-pay you should be able to hook into subscription status updates through the status update actions.

https://github.com/pronamic/wp-pay-core/blob/f220aa2ee979389cfcae782ff643b681ff85013b/src/Subscriptions/SubscriptionsDataStoreCPT.php#L761-L795

**Comment by knit-pay** [comment]
> @knit-pay you should be able to hook into subscription status updates through the status update actions.

Thanks
