### ISSUE TITLE
Issue with get_pronamic_payment_by_meta function

### ISSUE THREAD

**Issue by knit-pay** [pronamic/wp-pay-core#59]
`get_pronamic_payment_by_meta` function is no more returning payment with custom meta. We are using this function in the various webhook listener to find a payment. Kindly suggest.
https://github.com/pronamic/wp-pay-core/blob/1d52978095404ead043a0bd24c67ecde8e3ece92/includes/functions.php#L44

**Comment by rvdsteege** [comment]
If you need the payments to be queryable by the meta, you should make sure to add the key/value as post meta. Meta added through `$payment->set_meta( $key, $value )` is not queryable by default, as it is stored in the JSON object in the post content.

- https://github.com/pronamic/wp-pay-core/blob/4.0.2/src/Payments/PaymentsDataStoreCPT.php#L84
- https://github.com/pronamic/wp-pay-core/blob/4.0.2/src/Payments/PaymentsDataStoreCPT.php#L221-L251

It's advised to keep post minimum to a minimum, as this can have negative performance impact in various areas on larger sites.

**Comment by knit-pay** [comment]
Thanks for the suggestion.
