### ISSUE TITLE
Reconsider payment status `Reserved`?

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pay-core#66]
In https://github.com/pronamic/wp-pay-core/commit/ecd0b071c3eab6ec996cd33ca1b29e4cad754fdb we added the payment status `Reserved`. I think this is mainly due to support for Sisow pay later payment methods. We had an internal Basecamp to-do for this at the time:

https://basecamp.com/1810084/projects/10966871/todos/368810841

In https://github.com/pronamic/wp-pronamic-pay-mollie/pull/4 we discovered that Mollie uses a `authorized` payment / order status.

- https://docs.mollie.com/orders/status-changes
- https://docs.mollie.com/payments/status-changes

Is the term `authorized` more common in combination with `capture`?

- https://developer.paypal.com/api/nvp-soap/paypal-payments-standard/integration-guide/authcapture/
- https://docs.adyen.com/point-of-sale/capturing-payments
- https://support.stripe.com/questions/using-authorization-and-capture-with-paymentintents

**Comment by rvdsteege** [comment]
Yup, I 100% agree it should be `Authorized`.

_As a side note, we could maybe also change `Success` (iDEAL) to `Paid` sometime?_

**Comment by remcotolsma** [comment]
Added new payment status `Authorized` in https://github.com/pronamic/wp-pay-core/pull/68. Need to deprecate the `Reserved` payment status.

**Comment by remcotolsma** [comment]
Since Sisow is deprecated I removed all `Reserved` code.
