### ISSUE TITLE
WPML webhook issue

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pay-core#74]
I reverted the changes in b558f59fe0db563c72281985ae0ccb562402fa15 in https://github.com/pronamic/wp-pay-core/commit/1ae8defb283bedd00f8cdf1c5535299e17d9be31, i don't think we want to have WPML specific code in our library / plugin. WPML is listed in the known plugin conflicts list: https://github.com/pronamic/wp-pronamic-pay#wpml.

> Het kan nog wel zijn dat je een admin melding over een gewijzigde URL krijgt te zien als de terugkoppeling weer succesvol verwerkt wordt. Die melding heeft te maken met WPML, ik probeer daar ook verbetering in aan te brengen in een volgende plugin update.

_Internal HelpScout ticket:_ https://secure.helpscout.net/conversation/2008985225/24470/

I don't think we should make WPML problems our problem. Perhaps the big question here is whether we are doing something wrong or whether WPML is doing something wrong.

**Comment by rvdsteege** [comment]
Also in internal Help Scout ticket https://secure.helpscout.net/conversation/2028148672/24553/.

**Comment by remcotolsma** [comment]
I've been thinking about this for a while and I think we can improve on this. I think the following piece of code also isn't really scalable (`'nopaging' => true`) :

https://github.com/pronamic/wp-pay-core/blob/1afa5d029986ef85024d85622004fe3feeaac158/src/Webhooks/WebhookManager.php#L48-L61

Maybe we should use https://actionscheduler.org/ for this? Or maybe we should check if we received a webhook request in this last week/month?

I think we should take into account that administrators should also receive a warning as soon as the home URL and therefore webhook URL changes and therefore settings at the provider may need to be updated.

Jetpack has also some kind of 'identity crisis' feature for this?

https://github.com/Automattic/jetpack/blob/11927e513dfbd0b9d0126f11dda92b61f345991f/projects/packages/identity-crisis/src/class-identity-crisis.php

- `jetpack_url_mismatch`
- `jetpack_home_url_mismatch`
- `jetpack_site_url_mismatch`

Let's think about a better solution that also resolves this WPML conflict.

**Comment by remcotolsma** [comment]
This issue was still assigned to me and so I took a fresh look at this again. What I wonder is whether the mechanism we have built in has much added value. In its current state there are some issues with it and it is not very scalable. We currently have `5` gateways who trigger the `pronamic_pay_webhook_log_payment` action:

- Mollie → https://github.com/search?q=repo%3Apronamic%2Fwp-pronamic-pay-mollie%20pronamic_pay_webhook_log_payment&type=code
- OmniKassa → https://github.com/search?q=repo%3Apronamic%2Fwp-pronamic-pay-omnikassa-2%20pronamic_pay_webhook_log_payment&type=code
- DigiWallet → https://github.com/search?q=repo%3Apronamic%2Fwp-pronamic-pay-digiwallet%20pronamic_pay_webhook_log_payment&type=code
- Buckaroo → https://github.com/search?q=repo%3Apronamic%2Fwp-pronamic-pay-buckaroo%20pronamic_pay_webhook_log_payment&type=code
- Adyen → https://github.com/search?q=repo%3Apronamic%2Fwp-pronamic-pay-adyen%20pronamic_pay_webhook_log_payment&type=code

Especially for OmniKassa the webhook functionality is crucial to update the payment status? But do users need the current mechanism to discover and fix webhook issues? We could also add a extra note the payment edit page for pending payments that are tied to a gateway without `payment_status_request` supports?

```php
<?php if ( 'pending' === $payment->get_status() && $gateway->supports( 'webhook' ) && ! $gateway->supports( 'payment_status_request' ) && $payment->get_date() < $yesterday ) : ?>

	<div class="notice">
		De status van deze betaling staat al langer dan een dag in afwachting.
		De status zou automatisch via een bericht van je payment provider bijgewerkt moeten worden.
		Controleer in dit geval de status van deze betaling handmatig bij je payment provider.
		Mocht dit probleem vaker voorkomen controleer dan ook de webhook instellingen.
	</div>

<?php endif; ?>
```

The pending payments are already highlighted in the admin menu with a count badge.

**Comment by remcotolsma** [comment]
Removed in https://github.com/pronamic/wp-pay-core/commit/adddf1ecd205cf2fec245d744fbe25c613b84cc8, will work on a home URL change detector in https://github.com/pronamic/wp-pay-core/issues/102.
