### ISSUE TITLE
Case-sensitive `PaymentMethods::is_active()`

### ISSUE THREAD

**Issue by rvdsteege** [pronamic/wp-pay-core#83]
It came to our attention in a support ticket that the value of an option in the Ninja Forms payment methods field is case-sensitive. Within Ninja Forms, the `PaymentMethods::is_active( $payment_method )` method is used to check if the given payment method is active, before creating the payment.

Would it be beneficial to transform the payment method to lowercase in the `is_active()` method? Or would that be a potential issue if gateway add-ons can maybe register their own payment methods — with any constant to their liking — in the future?

_Internal Help Scout ticket: https://secure.helpscout.net/conversation/2067045031/24787/_

**Comment by remcotolsma** [comment]
Maybe related issue:

- https://github.com/pronamic/wp-pronamic-pay/issues/214

**Comment by remcotolsma** [comment]
> Would it be beneficial to transform the payment method to lowercase in the `is_active()` method? Or would that be a potential issue if gateway add-ons can maybe register their own payment methods — with any constant to their liking — in the future?

I'm not in favor of this, let's focus on making the Ninja Forms payment method field less error prone:

- https://github.com/pronamic/wp-pronamic-pay/issues/214

Automatically changing capital to lower case is not very obvious, if that can be avoided that would be nice.
