### ISSUE TITLE
Issue while using with Ultimate Member Plugin

### ISSUE THREAD

**Issue by knit-pay** [pronamic/wp-pay-core#88]
Hello Team

One of my clients restricted a form page for only logged-in users using the "Ultimate Member" Plugin. and this line of code is causing the issue. I tried to figure out the exact cause but could not find the same. This line of code stops the execution and `start_payment` function fails. Do you have any idea about the same? If we deactivate the Ultimate Member Plugin, everything starts working. I could not replicate the issue on my local server. Facing the issue on the client's server only.

https://github.com/pronamic/wp-pay-core/blob/bd707301f7a3e792413163fa8b155c24e631b23d/src/Plugin.php#L948

**Comment by rvdsteege** [comment]
We're not aware of any issues with payment start, but I guess Ultimate Member hooks into something triggered by the `\url_to_postid( $url )` function.

It's best to contact support with the error message you're running into via https://ultimatemember.com/support/ (unless the error is in Pronamic Pay; please feel free to re-open the issue in that case).
