### ISSUE TITLE
"We just need to update your install to the latest version" on fresh install

### ISSUE THREAD

**Issue by knit-pay** [pronamic/wp-pay-core#91]
# Issue
Getting `We just need to update your install to the latest version` notice even on fresh WordPress install.

# Expected Behaviour
This notice should appear only after plugin upgrade, not on fresh WordPress instance.

# Steps to replicate
1. install "Pronamic Pay" on Newly installed WordPress website.
2. Install WooCommerce.
3. You will see notice on the top

**Comment by rvdsteege** [comment]
This is a known issue with the current upgrade scripts implementation, but should be fixed indeed. We'll look into it to see how we can improve this. Thank you for your feedback!

**Comment by remcotolsma** [comment]
Related code:

https://github.com/pronamic/wp-pay-core/blob/10b78655eea7c641ee33b0fb0cccc26037074067/src/Admin/Install.php#L307-L344

https://github.com/pronamic/wp-pay-core/blob/10b78655eea7c641ee33b0fb0cccc26037074067/src/AbstractIntegration.php#L282-L293

https://github.com/pronamic/wp-pay-core/blob/10b78655eea7c641ee33b0fb0cccc26037074067/src/Admin/Install.php#L346-L398

**Comment by remcotolsma** [comment]
Thanks, this is fixed in https://github.com/pronamic/wp-pay-core/pull/94, will improve/simplify this further:

- https://github.com/pronamic/wp-pay-core/issues/95
